[package]
name = "tuto"
version = "0.1.0"
edition = "2024"

[dependencies]
creusot-std = "0.9.0"

[features]
solutions = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(creusot)'] }
